### PR TITLE
feat: optimizations

### PR DESCRIPTION
**Pull request by viceice**
* generate modern es2018 js code
* import tslib instead of embed in every file
* add vscode debugging stuff

### CODE REVIEW

**Comment by rarkins** [comment]
Released manually as 0.2.1

**Comment by viceice** [comment]
maybe the es2018 compilation brings some improvements. We should add the the `tslib` to renovate too, so we remove a lot duplicated code.

**Comment by rarkins** [comment]
image
 ?

**Comment by viceice** [comment]
this is normal, because some older libs (devdeps) depend on `tslib`< 2 which is incompatible with `tslib` >= 2

**Comment by viceice** [comment]
if you compile with typescript >= 3.9 you need tslib >=2.0, otherwise tslib<2.0

**Pull request merged**
